# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 14:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bathroom',
            name='house',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='housing.House'),
        ),
        migrations.AddField(
            model_name='kitchen',
            name='house',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='housing.House'),
        ),
        migrations.AlterField(
            model_name='house',
            name='subdivision',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='housing.Subdivision'),
        ),
    ]
