# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0002_auto_20170503_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='image',
            field=models.ImageField(default='housing/static/imgs/no-img.png', upload_to=b''),
        ),
    ]
