# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0003_house_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='image',
            field=models.ImageField(default='housing/static/imgs/no-img.png', upload_to='housing/static/imgs'),
        ),
    ]
