# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0004_auto_20170503_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdivision',
            name='image',
            field=models.ImageField(default='housing/static/imgs/no-img.png', upload_to='housing/static/imgs'),
        ),
    ]
