# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0005_subdivision_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='bathroom',
            name='image',
            field=models.ImageField(default='housing/static/imgs/no-img.png', upload_to='housing/static/imgs'),
        ),
        migrations.AddField(
            model_name='kitchen',
            name='image',
            field=models.ImageField(default='housing/static/imgs/no-img.png', upload_to='housing/static/imgs'),
        ),
        migrations.AddField(
            model_name='material',
            name='image',
            field=models.ImageField(default='housing/static/imgs/no-img.png', upload_to='housing/static/imgs'),
        ),
        migrations.AlterField(
            model_name='house',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='material',
            name='ppsf',
            field=models.FloatField(help_text='price per square foot'),
        ),
    ]
