# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0007_auto_20170503_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bathroom',
            name='image',
            field=models.ImageField(default='media/no-img.png', upload_to=b''),
        ),
        migrations.AlterField(
            model_name='house',
            name='image',
            field=models.ImageField(default='media/no-img.png', upload_to=b''),
        ),
        migrations.AlterField(
            model_name='kitchen',
            name='image',
            field=models.ImageField(default='media/no-img.png', upload_to=b''),
        ),
        migrations.AlterField(
            model_name='material',
            name='image',
            field=models.ImageField(default='media/no-img.png', upload_to=b''),
        ),
        migrations.AlterField(
            model_name='subdivision',
            name='image',
            field=models.ImageField(default='media/no-img.png', upload_to=b''),
        ),
    ]
